version: '3'
services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=BryDev
      - N8N_BASIC_AUTH_PASSWORD=011224
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/root/.n8n
    restart: always
volumes:
  n8n_data:
